### ISSUE TITLE
Assignment admin rework

### ISSUE THREAD

**Issue by StianJul** [devilry/devilry-django#1028]
This issue is just here to gather issues that are related.

### Related issues:
 - [x] #1021 Import options for assignment creation
 - [x] #1027 Warn admins that students lack examiner
 - [x] #971 [ui] Not all assignment warnings are displayed
