### ISSUE TITLE
Dependency bumps

### ISSUE THREAD

**Issue by torgeirl** [devilry/devilry-django#1149]
From dependabot:

- [x] `extend` from 3.0.0 to 3.0.2 (#1144)
- [x] `js-yaml` from 3.12.0 to 3.13.1 (#1145)
- [x] `lodash` from 4.17.11 to 4.17.19 (#1147)
- [x] `lodash` from 4.17.15 to 4.17.19 (#1148)
- [x] `qs` from 6.3.0 to 6.3.2 (#1154)
- [x] `tough-cookie` from 2.3.2 to 2.3.4 (#1155)
- [x] `httplib2` from 0.7.7 to 0.19.0 (#1163)
- [x] `elliptic` from 6.4.1 to 6.5.4 (#1167)
- [x] `ini` from 1.3.4/1.3.5 to 1.3.8 (#1168, #1169)
- [x] `djangorestframework` from 3.8.2 to 3.11.2 (#1170)
- [x] `pyyaml` from 3.13 to 5.4 (#1171)
- [x] `pygments` from 2.0 to 2.7.4 (#1172)
- [x] `y18n` from 3.2.1 to 3.2.2 (#1173)

**Comment by StianJul** [comment]
What has been done:
- Devilry updated to Django 3.1
- Dependencies updated (python and java) for the Django 3 upgrade.
- Code-migrations and test-fixes.
- Replaced model_mommy test-fixture library with model_bakery. model_mommy is no longer maintained and has been replaced by model_bakery.

Merge into `milestone-5.1`-branch, and will be released when ready.
