### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by jimma1** [devilry/devilry-django#935]
## Missing translations
The following is not translated because I cannot find the string/code i Devilry which sets the value or the translations will not work, by some odd reason.

Must make messages and translate the few words containing "passed/failed" before closing issue

### JS
Line 104 in `GradingConfigurationCustomTableWidget.js`. Det er her lagt til mulighet for å benytte javascript-translations hvis det er hvordan man ønsker å oversette `remove` knappen. Det er lagt til en utils mappe i `theme sin javascript` og her er filen `i18nFallbacks` kopiert fra en nyere versjon av ievv_jsbase enn det som Devilry benytter. 

### Edit Grade With Points
The form `EditGradePointsForm` is used when editing the grade points for an assignment. Here there is a help text field which has `ugettext_lazy` to it. When the help text is removed, the text disappear from the view. The text is translated in Poedit. Still, it will not show up in Norwegian in the view. 
![image](https://user-images.githubusercontent.com/10887266/35275181-374e6e24-003f-11e8-95f8-afb317a0f2e4.png)

Further there is a encoding problem when using the letter `å` in this view. After translating `passed` to `bestått` the following error is shown:
![image](https://user-images.githubusercontent.com/10887266/35276962-7a6534d0-0045-11e8-85f4-84a5da031692.png)

When looking at the hint, is says the following:
![image](https://user-images.githubusercontent.com/10887266/35276992-93014416-0045-11e8-9623-707c7ee66259.png)

I think this is sat in the template `grade-full.django.html`. However, there is not easy finding the string to encode into `utf-8` which I believe will fix this problem.

### Moving deadline for assignment
When a new deadline is sat, it is displayed in English when the language is sat to Norwegian in settings.

![image](https://user-images.githubusercontent.com/10887266/35274434-5553d754-003c-11e8-8f53-fcc6e26c8470.png)

## TODO
- [x] Translations in Poedit
- [x] Change Course to kurs in PoEdit
- [x] Go thru the views and find strings not marked for translations
- [x] Changes in english in UI
- [x] Provoke to see if num_groups and num_candidates have switched places in `%(num_groups)s students organized in %(num_candidates)s project groups`

### Changes in English in UI
- [x] Change `Courses can only be added to subject and department administrator permission groups.` to `Courses can only be added to course and department administrator permission groups` 
- [x] Find all places where `subject` is written and replace it with `course`
